var-default-image-swu: Make do_fetch depend on do_deploy task
When adding u-boot build artifacts listed in SRC_URI,
the artifacts should be built first otherwise this error occurs:
ERROR: var-default-image-swu-1.0-r0 do_fetch: Fetcher failure: Unable to find file
file:///home/natalia/var-ti-yocto/oe-layersetup/build/deploy-ti/images/am62x-var-som/tiboot3.bin anywhere

to fix it make do_fetch depend on u-boot-variscite:do_deploy task.

Signed-off-by: Natalia Kovalenko <natasha.k@variscite.com>